### ISSUE TITLE
Exposed Token

### ISSUE THREAD

**Issue by daminals** [SuperS123/discord-bot-test#1]
your token is exposed bro

**Comment by SuperS123** [comment]
That’s the point

**Comment by SuperS123** [comment]
If you do it, discord auto messages you saying we regen’d it

**Comment by daminals** [comment]
Then why wouldn't you make a readme that says that 🙄

**Comment by SuperS123** [comment]
I dont expect anyone to look at this repo, its only public because i needed discord to find it.
